### ISSUE TITLE
Readme suggestions

### ISSUE THREAD

**Issue by ericawu** [tessmichi/Fineas#21]
Make the "here's how to download and run my bot" section separate, so it's more obvious to readers

**Comment by tessmichi** [comment]
Add list of versions for each reference

**Comment by tessmichi** [comment]
Add description of how the bot works

**Comment by tessmichi** [comment]
Forgot to mark this as closed when I finished it yesterday in commit 37d5344a105359e56f3a05d5a30eb3e3492263da 

Also, see issue #27
